// module.exports = {
//   COMMUNITY_CHAT: "COMMUNITY_CHAT",
//   USER_CONNECTED: "USER_CONNECTED",
//   MESSASE_SENT: "MESSAGE_SENT",
//   MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
//   USER_DISCONNECTED: "USER_DISCONNECTED",
//   LOGOUT: "LOGOUT",
//   TYPING: "TYPING",
//   VERIFY_USER: "VERIFY_USER"
// };
